import { clues, grammarReflections, lessons, levels, phrases } from "./data.js";
import { studyCompassCounts } from "./study-compass.js";

const key = "prize2pride-japanese-tunisian-progress";
let activeLevel = "A0";
let activeLessonId = "a0-hello";
let state = JSON.parse(localStorage.getItem(key) || "{\"completed\":[],\"drafts\":{},\"savedPhrases\":[]}");
const $ = (id) => document.getElementById(id);
const persist = () => localStorage.setItem(key, JSON.stringify(state));
const lesson = () => lessons.find((item) => item.id === activeLessonId);

function renderLevels() { $("levels").innerHTML = levels.map((level) => `<button role="tab" aria-selected="${activeLevel === level.id}" class="${activeLevel === level.id ? "active" : ""}" data-level="${level.id}"><b>${level.label}</b><span>${level.title}</span><small dir="rtl">${level.arabic}</small></button>`).join(""); document.querySelectorAll("[data-level]").forEach((button) => button.addEventListener("click", () => { activeLevel = button.dataset.level; activeLessonId = lessons.find((item) => item.level === activeLevel && !state.completed.includes(item.id))?.id || lessons.find((item) => item.level === activeLevel).id; render(); })); }
function renderCompass() { const counts = studyCompassCounts(state, lessons.length, phrases.length); $("compass-stats").innerHTML = `<article><b>${counts.completed}/${lessons.length}</b><span>lesson routes completed</span><small dir="rtl">دروس مكمّلة في الجهاز</small></article><article><b>${counts.savedPhrases}/${phrases.length}</b><span>phrase cards saved</span><small dir="rtl">عبارات محفوظة محلياً</small></article><article><b>${counts.grammarDrafts}</b><span>grammar drafts prepared</span><small dir="rtl">مسوّدات قواعد في الجهاز</small></article>`; }
function renderLessonButtons() { $("lesson-buttons").innerHTML = lessons.filter((item) => item.level === activeLevel).map((item) => `<button class="lesson-button ${item.id === activeLessonId ? "active" : ""}" data-lesson="${item.id}">${state.completed.includes(item.id) ? "✓ " : ""}${item.title}<small>${item.arabic}</small></button>`).join(""); document.querySelectorAll("[data-lesson]").forEach((button) => button.addEventListener("click", () => { activeLessonId = button.dataset.lesson; render(); })); }
function renderWorkspace() { const item = lesson(); const grammar = grammarReflections[item.level]; $("level-title").textContent = `${activeLevel} · ${levels.find((level) => level.id === activeLevel).title}`; $("lesson-context").textContent = item.context; $("lesson-title").textContent = item.title; $("lesson-arabic").textContent = item.arabic; $("dialogue").innerHTML = item.turns.map(([speaker, japanese, support]) => `<p><b>${speaker}</b><span lang="ja">${japanese}</span><small>${support}</small></p>`).join(""); $("grammar-title").textContent = grammar.title; $("grammar-summary").textContent = grammar.summary; $("grammar-arabic").textContent = grammar.arabic; $("reflection-prompt").textContent = grammar.prompt; $("reflection-prompt-arabic").textContent = grammar.tunisianPrompt; $("reflection").setAttribute("aria-label", `${grammar.title}のための自分の日本語の下書き`); $("reflection").value = state.drafts[item.id] || ""; $("complete-lesson").textContent = state.completed.includes(item.id) ? "✓ この端末に記録済み · مسجّلة في الجهاز" : "完成として記録 · سجّلها كمكمّلة"; }
function renderClues() { $("clue-options").innerHTML = clues.map((clue, index) => `<button data-clue="${index}">${index + 1}. ${clue}</button>`).join(""); document.querySelectorAll("[data-clue]").forEach((button) => button.addEventListener("click", () => { $("clue-response").textContent = "اخترت إشارة. ارجع للنص وفسّر بكلماتك علاش لفتت انتباهك. · You selected a clue. Return to the text and explain why it matters."; })); }
function renderMosaic() { state.savedPhrases ||= []; $("phrase-mosaic").innerHTML = phrases.filter((item) => item.level === activeLevel).map((item) => { const saved = state.savedPhrases.includes(item.id); return `<button class="phrase-card ${saved ? "saved" : ""}" data-phrase="${item.id}" aria-pressed="${saved}"><span>${item.japanese}</span><b dir="rtl">${item.tunisian}</b><small>${item.cue}</small><em>${saved ? "✓ مراجعة محلياً" : "علّمها للمراجعة"}</em></button>`; }).join(""); document.querySelectorAll("[data-phrase]").forEach((button) => button.addEventListener("click", () => { const id = button.dataset.phrase; state.savedPhrases = state.savedPhrases.includes(id) ? state.savedPhrases.filter((item) => item !== id) : [...state.savedPhrases, id]; persist(); renderMosaic(); })); }
function render() { renderLevels(); renderCompass(); renderLessonButtons(); renderWorkspace(); renderClues(); renderMosaic(); }
$("speak-dialogue").addEventListener("click", () => { const utterance = new SpeechSynthesisUtterance(lesson().turns.map((turn) => turn[1]).join(" ")); utterance.lang = "ja-JP"; speechSynthesis.cancel(); speechSynthesis.speak(utterance); });
$("complete-lesson").addEventListener("click", () => { if (!state.completed.includes(activeLessonId)) state.completed.push(activeLessonId); persist(); render(); });
$("save-reflection").addEventListener("click", () => { state.drafts[activeLessonId] = $("reflection").value; persist(); $("save-status").textContent = "この端末に保存しました · تخزّنت في جهازك"; });
$("start-learning").addEventListener("click", () => $("lesson-workspace").scrollIntoView({ behavior: "smooth" }));
render();
