export const levels = [
  { id: "A0", label: "A0", title: "First contact", arabic: "أول خطوة" },
  { id: "A1", label: "A1", title: "Everyday exchange", arabic: "حياة يومية" },
  { id: "A2", label: "A2", title: "Study & movement", arabic: "قراية وتنقّل" },
  { id: "B1", label: "B1", title: "Projects & ideas", arabic: "مشاريع وأفكار" },
  { id: "B2", label: "B2", title: "Academic presence", arabic: "حضور أكاديمي" },
];

export const lessons = [
  { id: "a0-hello", level: "A0", context: "Greeting · التحية", title: "はじめまして", arabic: "أول تعارف بسيط", turns: [["A", "はじめまして。わたしはサミです。", "Nice to meet you. I’m Sami."], ["B", "はじめまして。チュニジアから来ました。", "Nice to meet you. I came from Tunisia."], ["A", "よろしくお願いします。", "I look forward to knowing you."]] },
  { id: "a0-name", level: "A0", context: "Name · الاسم", title: "お名前は？", arabic: "سؤال محترم على الاسم", turns: [["A", "お名前は？", "What is your name?"], ["B", "ラウエドです。", "I’m Raoued."], ["A", "ラウエドさん、よろしく。", "Nice to meet you, Raoued."]] },
  { id: "a1-cafe", level: "A1", context: "Café · قهوة", title: "コーヒーをお願いします", arabic: "طلب بسيط في قهوة", turns: [["A", "コーヒーをお願いします。", "Coffee, please."], ["B", "ホットですか、アイスですか？", "Hot or iced?"], ["A", "アイスでお願いします。", "Iced, please."]] },
  { id: "a1-route", level: "A1", context: "Direction · طريق", title: "駅はどこですか", arabic: "كيفاش تسأل على المحطّة", turns: [["A", "すみません、駅はどこですか？", "Excuse me, where is the station?"], ["B", "あそこを右です。", "It is to the right over there."], ["A", "ありがとうございます。", "Thank you."]] },
  { id: "a2-class", level: "A2", context: "Study · قراية", title: "授業のあとで", arabic: "تنظيم وقت بعد الدرس", turns: [["A", "授業のあとで、図書館へ行きませんか？", "Would you like to go to the library after class?"], ["B", "いいですね。三時はどうですか？", "Sounds good. How about three?"], ["A", "三時に会いましょう。", "Let’s meet at three."]] },
  { id: "a2-travel", level: "A2", context: "Travel · سفر", title: "予約を確認します", arabic: "تأكيد حجز بطريقة واضحة", turns: [["A", "予約を確認したいです。", "I’d like to confirm my reservation."], ["B", "お名前をお願いします。", "May I have your name?"], ["A", "ラウエド・ファデルです。", "It is Raoued Fadhel."]] },
  { id: "b1-project", level: "B1", context: "Project · مشروع", title: "提案を共有します", arabic: "مشاركة اقتراح في مشروع", turns: [["A", "提案の目的を共有します。", "I will share the purpose of the proposal."], ["B", "利用者の意見も入れましょう。", "Let’s include users’ views too."], ["A", "はい、次の版に反映します。", "Yes, I will reflect that in the next version."]] },
  { id: "b1-meeting", level: "B1", context: "Meeting · اجتماع", title: "確認したい点があります", arabic: "طلب توضيح في اجتماع", turns: [["A", "確認したい点があります。", "There is a point I would like to confirm."], ["B", "どうぞ。", "Please go ahead."], ["A", "期限を一週間延ばせますか？", "Could we extend the deadline by one week?"]] },
  { id: "b2-seminar", level: "B2", context: "Seminar · ندوة", title: "根拠を説明します", arabic: "شرح الحجج في ندوة", turns: [["A", "この結論の根拠を説明します。", "I will explain the basis for this conclusion."], ["B", "別の視点はありますか？", "Is there another perspective?"], ["A", "地域の経験からも検討できます。", "We can consider it from regional experience as well."]] },
  { id: "b2-network", level: "B2", context: "Network · علاقات", title: "今後も連絡を取りましょう", arabic: "بناء علاقة مهنية محترمة", turns: [["A", "お話しできてよかったです。", "I am glad we could talk."], ["B", "こちらこそ、ありがとうございました。", "Likewise, thank you."], ["A", "今後も連絡を取りましょう。", "Let’s stay in touch."]] },
  { id: "a0-country", level: "A0", context: "Origin · الأصل", title: "どちらから来ましたか", arabic: "تسأل على الأصل باحترام", turns: [["A", "どちらから来ましたか？", "Where are you from?"], ["B", "チュニジアから来ました。", "I came from Tunisia."], ["A", "ようこそ。", "Welcome."]] },
  { id: "a0-study", level: "A0", context: "First study · أول قراية", title: "日本語は初めてです", arabic: "تقول إنك بديت الياباني", turns: [["A", "日本語は初めてですか？", "Is this your first time with Japanese?"], ["B", "はい、少しずつ勉強しています。", "Yes, I am studying little by little."], ["A", "ゆっくりで大丈夫です。", "Slowly is fine."]] },
  { id: "a0-thanks", level: "A0", context: "Thanks · شكر", title: "どうもありがとうございます", arabic: "تشكر بطريقة واضحة", turns: [["A", "手伝ってくれて、ありがとうございます。", "Thank you for helping me."], ["B", "どういたしまして。", "You are welcome."], ["A", "助かりました。", "That helped me."]] },
  { id: "a0-goodbye", level: "A0", context: "Goodbye · وداع", title: "また会いましょう", arabic: "وداع مع موعد بسيط", turns: [["A", "今日はありがとうございました。", "Thank you for today."], ["B", "こちらこそ。", "Likewise."], ["A", "また会いましょう。", "Let’s meet again."]] },
  { id: "a1-shop", level: "A1", context: "Shop · محل", title: "これをください", arabic: "طلب حاجة من محل", turns: [["A", "これをください。", "This one, please."], ["B", "小さいサイズもあります。", "We also have a small size."], ["A", "では、小さいサイズをお願いします。", "Then, the small size please."]] },
  { id: "a1-time", level: "A1", context: "Time · وقت", title: "今、何時ですか", arabic: "تسأل على الوقت", turns: [["A", "すみません、今、何時ですか？", "Excuse me, what time is it now?"], ["B", "二時半です。", "It is two thirty."], ["A", "ありがとうございます。", "Thank you."]] },
  { id: "a1-repeat", level: "A1", context: "Clarify · وضّح", title: "もう一度お願いします", arabic: "تطلب إعادة الكلام بالراحة", turns: [["A", "すみません、もう一度お願いします。", "Excuse me, one more time please."], ["B", "はい、ゆっくり話します。", "Yes, I will speak slowly."], ["A", "助かります。", "That helps."]] },
  { id: "a1-message", level: "A1", context: "Message · رسالة", title: "後で連絡します", arabic: "تبعث خبر بعدين", turns: [["A", "今日は少し忙しいです。", "I am a little busy today."], ["B", "分かりました。", "I understand."], ["A", "後で連絡します。", "I will contact you later."]] },
  { id: "a2-change", level: "A2", context: "Plan · خطة", title: "予定を変更したいです", arabic: "تبدّل موعد بطريقة مهذبة", turns: [["A", "予定を変更したいです。", "I would like to change the schedule."], ["B", "何日に変更しますか？", "Which day would you like to change it to?"], ["A", "金曜日にしたいです。", "I would like Friday."]] },
  { id: "a2-appointment", level: "A2", context: "Appointment · موعد", title: "三時に予約があります", arabic: "توضّح إن عندك موعد", turns: [["A", "三時に予約があります。", "I have an appointment at three."], ["B", "お名前を確認します。", "I will confirm your name."], ["A", "お願いします。", "Please."]] },
  { id: "a2-document", level: "A2", context: "Work · خدمة", title: "資料を送ります", arabic: "ترسل وثيقة للخدمة", turns: [["A", "資料をメールで送ります。", "I will send the materials by email."], ["B", "受け取ったら確認します。", "I will check them when I receive them."], ["A", "よろしくお願いします。", "Thank you in advance."]] },
  { id: "a2-bus", level: "A2", context: "City · مدينة", title: "大学へ行きますか", arabic: "تسأل على الباص والجامعة", turns: [["A", "このバスは大学へ行きますか？", "Does this bus go to the university?"], ["B", "次の停留所で乗り換えます。", "You change at the next stop."], ["A", "分かりました。", "I understand."]] },
  { id: "b1-email", level: "B1", context: "Email · إيميل", title: "メールを確認していただけますか", arabic: "تطلب مراجعة إيميل باحترام", turns: [["A", "メールを確認していただけますか？", "Could you review the email?"], ["B", "はい、午後に返事します。", "Yes, I will reply this afternoon."], ["A", "ありがとうございます。", "Thank you."]] },
  { id: "b1-feedback", level: "B1", context: "Feedback · رأي", title: "意見を聞かせてください", arabic: "تطلب رأي على اقتراح", turns: [["A", "この提案について、意見を聞かせてください。", "Please share your thoughts on this proposal."], ["B", "利用者の時間も考えたいです。", "I would also like to consider users’ time."], ["A", "大切な視点ですね。", "That is an important perspective."]] },
  { id: "b1-plan", level: "B1", context: "Planning · تخطيط", title: "役割を分けましょう", arabic: "تقسيم الأدوار في فريق", turns: [["A", "役割を分けましょう。", "Let’s divide the roles."], ["B", "私は資料をまとめます。", "I will organize the materials."], ["A", "私は連絡を担当します。", "I will handle communication."]] },
  { id: "b1-progress", level: "B1", context: "Progress · تقدّم", title: "進み方を共有します", arabic: "تشارك تقدّم المشروع", turns: [["A", "進み方を共有します。", "I will share our progress."], ["B", "難しかった点はありますか？", "Were there any difficult points?"], ["A", "時間の調整が必要でした。", "We needed to adjust the timing."]] },
  { id: "b2-interview", level: "B2", context: "Interview · مقابلة", title: "経験について説明します", arabic: "تشرح تجربتك في مقابلة", turns: [["A", "これまでの経験について説明します。", "I will explain my experience so far."], ["B", "この役割に何を生かせますか？", "What can you bring to this role?"], ["A", "チームで学んだ調整力を生かせます。", "I can use the coordination skills I learned in teams."]] },
  { id: "b2-summary", level: "B2", context: "Summary · تلخيص", title: "要点をまとめます", arabic: "تلخّص النقاط الأساسية", turns: [["A", "議論の要点をまとめます。", "I will summarize the key points of the discussion."], ["B", "次の判断は何ですか？", "What is the next decision?"], ["A", "追加の資料を見てから決めます。", "We will decide after seeing additional materials."]] },
  { id: "b2-collaboration", level: "B2", context: "Collaboration · تعاون", title: "条件を確認しましょう", arabic: "تراجع الشروط مع شريك", turns: [["A", "協力の条件を確認しましょう。", "Let’s confirm the conditions of collaboration."], ["B", "役割と期限を明確にしたいです。", "I would like to clarify roles and deadlines."], ["A", "文書にして共有します。", "I will put them in writing and share them."]] },
  { id: "b2-research", level: "B2", context: "Research · بحث", title: "方法を見直す必要があります", arabic: "تراجع طريقة البحث", turns: [["A", "この方法を見直す必要があります。", "We need to review this method."], ["B", "どの部分を変えますか？", "Which part will we change?"], ["A", "参加者の声をもっと聞きます。", "We will listen more to participants’ voices."]] },
];

export const grammarReflections = {
  A0: { title: "は・ですを自分の紹介に使う", summary: "名前、出身、はじめての学びを示す短い形に注目します。", arabic: "ركّز على شكل قصير باش تقدّم اسمك، أصلك، وبداية تعلّمك.", prompt: "自分について一文を書いてみましょう。答えのモデルはありません。", tunisianPrompt: "اكتب جملة على روحك بالياباني. ما فماش نموذج جواب حاضر." },
  A1: { title: "お願いします・ですかで丁寧に聞く", summary: "依頼、質問、聞き直しの場面で丁寧さがどう動くかを観察します。", arabic: "لاحظ كيفاش الأدب يخدم في الطلب، السؤال، وطلب الإعادة.", prompt: "この場面で丁寧に言いたいことを一文で準備しましょう。", tunisianPrompt: "حضّر جملة وحدة تحب تقولها بأدب في الموقف هذا." },
  A2: { title: "たいです・ませんかで予定を組む", summary: "希望、招待、確認の形を場面の目的といっしょに読みます。", arabic: "اقرا شكل الرغبة، الدعوة، والتأكيد مع هدف الموقف.", prompt: "時間や次の行動を入れた自分の文を下書きしましょう。", tunisianPrompt: "اكتب مسودّة لجملتك فيها وقت أو خطوة جاية." },
  B1: { title: "ていただけますかで協働を開く", summary: "確認、意見、役割を頼むときの丁寧な協働表現に注目します。", arabic: "ركّز على عبارات التعاون المهذّبة كي تطلب توضيح، رأي، أو دور.", prompt: "チームに頼みたいことを自分の文で書いてみましょう。", tunisianPrompt: "اكتب بجملتك الحاجة اللي تحب تطلبها من الفريق." },
  B2: { title: "について・必要がありますで根拠を組む", summary: "説明、条件、見直しをつなぐ表現が論点をどう組み立てるかを観察します。", arabic: "لاحظ كيفاش عبارات الشرح، الشروط، والمراجعة تركّب الفكرة والحجّة.", prompt: "根拠か次の判断を含む自分の文を準備しましょう。", tunisianPrompt: "حضّر جملة من عندك فيها حجّة أو قرار جاي." },
};

export const clues = ["Purpose words such as 目的", "A time or place signal", "A phrase that shows a respectful request"];
export const phrases = [
  { id: "a0-greeting", level: "A0", japanese: "はじめまして", tunisian: "تشرفنا", cue: "A respectful first encounter" },
  { id: "a0-thanks", level: "A0", japanese: "ありがとうございます", tunisian: "يعطيك الصحة", cue: "A clear thank-you" },
  { id: "a1-request", level: "A1", japanese: "お願いします", tunisian: "من فضلك", cue: "A concise request" },
  { id: "a1-question", level: "A1", japanese: "どこですか？", tunisian: "وين موجود؟", cue: "A location question" },
  { id: "a2-invitation", level: "A2", japanese: "行きませんか？", tunisian: "ما نمشيوش؟", cue: "An invitation to join" },
  { id: "a2-time", level: "A2", japanese: "会いましょう", tunisian: "نتقابلوا", cue: "A shared plan" },
  { id: "b1-clarify", level: "B1", japanese: "確認したい点があります", tunisian: "عندي نقطة نحب نوضّحها", cue: "A respectful clarification" },
  { id: "b1-purpose", level: "B1", japanese: "目的を共有します", tunisian: "باش نشارك الهدف", cue: "A project opening" },
  { id: "b2-evidence", level: "B2", japanese: "根拠を説明します", tunisian: "باش نفسّر الحجج", cue: "An academic justification" },
  { id: "b2-network", level: "B2", japanese: "連絡を取りましょう", tunisian: "نخليو الاتصال بيناتنا", cue: "A professional continuation" },
  { id: "a0-origin", level: "A0", japanese: "チュニジアから来ました", tunisian: "جيت من تونس", cue: "A clear origin statement" },
  { id: "a1-repeat", level: "A1", japanese: "もう一度お願いします", tunisian: "عاود من فضلك", cue: "A respectful request to repeat" },
  { id: "a2-change", level: "A2", japanese: "変更したいです", tunisian: "نحب نبدّل", cue: "A calm plan change" },
  { id: "b1-role", level: "B1", japanese: "役割を分けましょう", tunisian: "خلّينا نقسّم الأدوار", cue: "A project coordination step" },
  { id: "b2-summary", level: "B2", japanese: "要点をまとめます", tunisian: "باش نلخّص النقاط", cue: "An academic synthesis move" },
];
